CREATE TABLE users (
    id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '用户ID',
    email         VARCHAR(255) NOT NULL UNIQUE COMMENT '登录邮箱, 全局唯一',
    password_hash VARCHAR(255) NOT NULL COMMENT 'bcrypt 哈希后的密码',
    nickname      VARCHAR(50)  NOT NULL DEFAULT '' COMMENT '用户昵称',
    created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

